spring:
  application:
    name: "Zuul-Gateway"

server:
  port: 9090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: {EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true


zuul:
  routes:
    helloWorld:
      services:
        path: /helloservice/**
        serviceId: HELLOSERVICE
        stripPrefix: true



